version: '3.8'

services:
  laravel.app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: laravel-app:latest
    volumes:
      - '.:/var/www/html'
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - laravel
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - '.:/var/www/html:ro'
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
    depends_on:
      - laravel.app
    networks:
      - laravel

  mysql:
    container_name: mysql
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'prod-mysql:/var/lib/mysql'
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  prod-mysql:
    driver: local
