name: Staging deployment

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          IMAGE_TAG=library-image:${{ github.run_number }}
          docker build . --file Dockerfile --tag $IMAGE_TAG --no-cache
          docker save $IMAGE_TAG -o library-image.tar
        env:
          IMAGE_TAG: library-image:${{ github.run_number }}

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: library-image
          path: library-image.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: library-image

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Transfer Docker image to Droplet
        run: |
          scp -o StrictHostKeyChecking=no library-image.tar root@142.93.14.79:/home/laravel/book-library

      - name: Deploy to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@142.93.14.79 << 'EOF'
          set -ex
          cd /home/laravel/book-library
          docker system prune -a -f
          docker volume prune -a -f
          docker system prune -a -f --volumes
          docker-compose down
          docker load -i library-image.tar
          docker-compose up -d --force-recreate --no-deps
          EOF
