name: Staging deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s) --no-cache

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Deploy to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@142.93.14.79 << 'EOF'
          cd /home/laravel/book-library
          docker system prune -f
          docker volume prune -f
          git reset --hard
          git clean -fd
          git pull origin main
          git pull origin main
          docker-compose down
          docker-compose pull
          docker-compose -f docker-compose.prod.yml up --build -d
          EOF
